### ISSUE TITLE
TypeError: Cannot read property 'getOctokit' of undefined

### ISSUE THREAD

**Issue by dvirtz** [setare/git-changes-action#33]
I get this error while trying to use this action

```
(node:2208) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getOctokit' of undefined
    at /home/runner/work/_actions/setare/git-changes-action/v0.1.2/webpack:/typescript-action/lib/main.js:41:1
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/setare/git-changes-action/v0.1.2/webpack:/typescript-action/lib/main.js:27:1
    at new Promise (<anonymous>)
    at module.exports.__webpack_modules__.3109.__awaiter (/home/runner/work/_actions/setare/git-changes-action/v0.1.2/webpack:/typescript-action/lib/main.js:23:1)
    at run (/home/runner/work/_actions/setare/git-changes-action/v0.1.2/webpack:/typescript-action/lib/main.js:39:1)
    at Object.3109 (/home/runner/work/_actions/setare/git-changes-action/v0.1.2/webpack:/typescript-action/lib/main.js:86:1)
    at __webpack_require__ (/home/runner/work/_actions/setare/git-changes-action/v0.1.2/webpack:/typescript-action/webpack/bootstrap:20:1)
    at /home/runner/work/_actions/setare/git-changes-action/v0.1.2/webpack:/typescript-action/webpack/startup:4:1
    at Object.<anonymous> (/home/runner/work/_actions/setare/git-changes-action/v0.1.2/dist/index.js:7628:12)
(node:2208) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2208) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The step is defined with
```yaml
      - name: "File generation check"
        uses: setare/git-changes-action@v0.1.2
        with:
          github_token: ${{ github.token }}
```

**Comment by dvirtz** [comment]
Upgrading to 0.1.4 fixed this.
You might wanna update the readme with the latest version.
